before_install:
  - wget https://github.com/spf13/hugo/releases/download/v0.18/hugo_0.18-64bit.deb
  - sudo dpkg -i hugo_0.18-64bit.deb

before_script:
  - git config --global user.name 'rokett'
  - git config --global user.email 'rokett_deploy@something.com'

script:
  - hugo

after_success:
  - mkdir .deploy
  - cd .deploy
  - git init
  - git remote add origin $DEPLOY_REPO
  - cp -r ../public/* .
  - git add -A .
  - git commit -m 'Site updated'
  - git push --force --quiet origin master
